### ISSUE TITLE
Paper from BlackboxNLP workshop at EMNLP 2018

### ISSUE THREAD

**Issue by Shujian2015** [lopusz/awesome-interpretable-machine-learning#2]
There 20 papers (from the Workshop on 'Analyzing and interpreting neural networks for NLP' (BlackboxNLP), EMNLP 2018) can fit in the topic: 

https://arxiv.org/search/advanced?advanced=&terms-0-operator=AND&terms-0-term=BlackboxNLP&terms-0-field=comments&terms-1-operator=OR&terms-1-term=Analyzing+interpreting+neural+networks+NLP&terms-1-field=comments&classification-physics_archives=all&date-filter_by=all_dates&date-year=&date-from_date=&date-to_date=&date-date_type=submitted_date&abstracts=show&size=200&order=-announced_date_first

**Comment by lopusz** [comment]
Very interesting Workshop! For now I added it to Venues section together with your arXiv search link, providing list of papers.

Thank you very much for your contribution!
